hospitais/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.views.static import serve
from django.conf import settings
from hospitalapp.views import index, criar_post, editar_post, deletar_post
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='hospitais/index.html')),
    path('blog/', index, name="blog"),
    path('criar_post/', criar_post, name="criar_post"),
    path('editar/<int:id>', editar_post, name="editar"),
    path('deletar/<int:id>', deletar_post, name="deletar"),
    path('', include('usuarios.urls')),
    url(r'^img/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import criar_usuario

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(

        template_name='usuarios/form_login.html'),
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(),
         name='logout'),
    path('cadastre-se/', criar_usuario, name='cadastre_se'),
]

hospitalapp/models.py
from django.db import models
from PIL import Image


# Create your models here.
class Hospital(models.Model):
    nome_hospital = models.TextField(max_length=200)
    foto = models.ImageField(null=True, blank=True)
    desc_hospital = models.TextField(max_length=200)
    tipo_hospital = models.TextField(max_length=200)
    conceito_hospital = models.TextField(max_length=500)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        im = Image.open(self.foto.path)
        # novo_tamanho =
        im.thumbnail((300, 380))
        im.save(self.foto.path)

    def foto_url(self):
        if self.foto and hasattr(self.foto, 'url'):
            return self.foto.url
        else:
            return "img/placeholder.png"

    def __str__(self):
        return self.nome_hospital

# Posts models


class Post(models.Model):
    titulo = models.TextField(max_length=200)
    descricao = models.TextField(max_length=200)
    foto = models.ImageField(null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        im = Image.open(self.foto.path)
        # novo_tamanho =
        im.thumbnail((300, 380))
        im.save(self.foto.path)

    def foto_url(self):
        if self.foto and hasattr(self.foto, 'url'):
            return self.foto.url
        else:
            return "img/placeholder.png"

    def __str__(self):
        return self.titulo


# Posts models
class TelaInicial(models.Model):
    titulo_cabebalho = models.TextField(max_length=200)
    titulo = models.TextField(max_length=200)
    descricao = models.TextField(max_length=200)
    
    box_1_titulo = models.TextField(null=True, blank=True)
    box_1_descricao = models.TextField(null=True, blank=True)
    box_1_foto = models.ImageField(null=True, blank=True)
    
    box_2_titulo = models.TextField(null=True, blank=True)
    box_2_descricao = models.TextField(null=True, blank=True)
    box_2_foto = models.ImageField(null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        im = Image.open(self.box_1_foto.path)
        im.thumbnail((300, 380))
        im.save(self.box_1_foto.path)

    def foto_url(self):
        if self.box_1_foto and hasattr(self.box_1_foto, 'url'):
            return self.box_1_foto.url
        else:
            return "img/placeholder.png"

    def __str__(self):
        return self.titulo

usuarios/models.py
from django.db import models

# Create your models here.

hospitalapp/forms.py
from django import forms
from .models import Hospital, Post


class Hospitalform(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = '__all__'
        # widgets = {
        #     'desc_hospital': forms.TextField(attrs={'class': 'myfieldclass'}),
        # }
        
class PostsForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        # widgets = {
        #     'desc_hospital': forms.TextField(attrs={'class': 'myfieldclass'}),
        # }

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UsuarioForm(UserCreationForm):
    email = forms.EmailField(max_length=200)
    
    class Meta:
        model = User
        fields = ['username', 'email']

hospitalapp/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from .forms import PostsForm, Hospitalform
from .models import Post, TelaInicial
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.contrib import messages

# Create your views here.


def index(request):
    tela_inicial = TelaInicial.objects.all()
    posts = Post.objects.all()
    busca = request.GET.get('search')
    if busca:
        posts = Post.objects.filter(titulo__icontains=busca)
    return render(request, 'hospitais/index.html', {'posts': posts, 'telainicial': tela_inicial})


# def posts(request):
#     posts = Post.objects.all()
#     busca = request.GET.get('search')
#     if busca:
#         posts = Post.objects.filter(titulo__icontains=busca)
#     return render(request, "hospitais/jornal.html", {'hospitais': posts})


def criar_post(request):
    form = PostsForm(request.POST)
    posts = Post.objects.all()
    tela_inicial = TelaInicial.objects.all()
    if request.method == "POST":
        form = PostsForm(request.POST, request.FILES)
    if form.is_valid():
        post = form.save()
        post.save()
        messages.success(request, 'Post criado com sucesso.')
        form = PostsForm()

    return render(request, 'posts/criar_post.html', {'form': form, 'posts': posts, 'telainicial': tela_inicial})


def editar_post(request, id):
    post = get_object_or_404(Post, pk=id)
    form = Hospitalform(instance=post)
    if (request.method == 'POST'):
        form = Hospitalform(request.POST, request.FILES, instance=post)
        if (form.is_valid()):
            form.save()
            return redirect('index')
        else:
            return render(request, "posts/editar_post.html", {'form': form, 'post': post})
    else:
        return render(request, "posts/editar_post.html", {'form': form, 'post': post})


def deletar_post(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.delete()
        return redirect('index')
    return render(request, 'posts/deletar_post.html', {'post': post})

usuarios/views.py
from django.shortcuts import render, redirect
from .forms import UsuarioForm
from hospitalapp.forms import Post

# Create your views here.


def criar_usuario(request):
    form = UsuarioForm(request.POST)
    posts = Post.objects.all()
    if request.method == "POST":
        form = UsuarioForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save()
            obj.save()
            return redirect('login')
    return render(request, 'usuarios/cadastre-se.html', {'form': form, 'posts': posts})

templates/hospitais/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>T1 - O portal de notícias número 1</title>
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/assets/css/global.css" />
    <style>
      .material-icons {
        font-family: 'Material Icons';
        font-style: normal;
        font-size: 28px; /* Preferred icon size */
        display: inline-block;
        line-height: 1;
        text-transform: none;
        letter-spacing: normal;
        word-wrap: normal;
        white-space: nowrap;
        direction: ltr;
        -webkit-font-smoothing: antialiased;
        text-rendering: optimizeLegibility;
        -moz-osx-font-smoothing: grayscale;
        font-feature-settings: 'liga';
      }
    </style>
  </head>
  <body>
    <div class="glbbarrawidget">
      <div class="main" style="display:flex">
        <div class="glbbarrawidget-left">
        {{ user.username|upper }} está logado.
        </div>
        <div class="glbbarrawidget-right">
          {% if not user.is_authenticated %}
          <a href="{% url 'cadastre_se' %}">CADASTRE-SE</a>
          <a href="{% url 'login' %}">ENTRAR</a>
          {% else %} 
          <a href="{% url 'admin:index' %}">PAINEL ADMINISTRATIVO</a>
          <a href="{% url 'criar_post' %}">CRIAR POSTAGEM</a>
          <a href="{% url 'logout' %}">SAIR</a>
          {% endif %}
        </div>
      </div>
    </div>
    <!-- CABEÇALHO -->
    <header>
      <div class="main">
        <div class="header-left">
          <span class="material-icons"> menu </span>
          MENU
        </div>
        <div class="header-center">
          <a href="{% url 'blog'%}"><img src="/static/assets/img/t1-icone.svg" width="60" alt="" /></a>
        </div>

        <div class="header-right">
          <form method="GET">
            <input
              placeholder="BUSCAR"
              type="search"
              value="BUSCAR"
              name="search"
              id="busca-campo"
              autocomplete="off"
              tabindex="1"
              class=""
            />
          </form>
        </div>
      </div>
    </header>

    <main class="main">
      <section class="o-que-foi-noticia-nesta-sexta main">
        <div class="day-noticia">O que foi notícia nesta sexta</div>
        <div class="day-resumo">
          <a>
            <span>Resumo do dia</span>
            <svg
              class="pirulito__link-more__icon"
              xmlns="http://www.w3.org/2000/svg"
              width="12"
              height="12"
              viewBox="5 5 12 12"
            >
              <path d="M13 10V8l5 4-5 4v-2H6v-4h7z"></path>
              <path fill="none" d="M5 5h14v14H5V5z"></path>
            </svg>
          </a>
        </div>
      </section>
      {% include "hospitais/noticia_principal.html" %}
      {% block content %} {% endblock content %}
    </main>

    <footer class="footer">
      <div class="main">
        <div class="footer_div_left">
          <img
            id="cor-primaria"
            src="public/assets/img/t1-icone.svg"
            width="40"
            alt=""
          />
          <!-- <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 516 308"
            id="cor-primaria"
          >
            <path
              fill="currentColor"
              fill-rule="evenodd"
              d="M0 208.716C0 263.56 50.353 308 112.558 308h224.66V118.447H212.173v94.417h-59.39c-15.54 0-28.157-11.125-28.157-24.828V95.97c0-13.68 7.63-24.826 23.16-24.826h100.467L304.525.47H112.558C50.353.47 0 49.482 0 104.34v104.376zM387.186 308H512V24.832C512 11.13 499.408 0 483.868 0h-123.05l-56.292 70.95h54.523c15.538 0 28.136 11.123 28.136 24.817V308z"
            ></path>
          </svg> -->
          Últimas notícias
          <span class="footer__copyright"
            >© Copyright 2000-2020 Lorem ipsum dolor sit amet consectetur
            adipisicing.</span
          >
        </div>
        <div class="footer_div_right">
          <div class="footer__service">
            <ul class="footer__service-list">
              <li class="footer__service-list-item">
                <a href="#" title="princípios editoriais"
                  >Princípios editoriais</a
                >
              </li>
              <li class="footer__service-list-item">
                <a href="#">Política de privacidade</a>
              </li>
              <li class="footer__service-list-item">
                <a href="#" title="minha conta">Minha conta</a>
              </li>
              <li class="footer__service-list-item">
                <a href="h#" title="anuncie conosco">Anuncie conosco</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

templates/hospitais/index.html
{% extends 'hospitais/base.html' %} 
  {% block content %}
{% include "hospitais/noticias_cards.html" %}
{% endblock content %}

     

templates/hospitais/noticia_principal.html
<section class="noticias main">
  <div>
    <h1>{{telainicial.0.titulo_cabebalho}}</h1>
    <div class="caixa">
      <span class="noticia-titulo"> {{telainicial.0.titulo}} </span>
      <span class="subtitulo">{{telainicial.0.descricao}}</span>
    </div>
  </div>
  <div class="container">
    <div class="box">
      <div
        class="inner-box"
        style="
          background: url(../img/placeholder-grande.png) no-repeat;
          background-size: 100% 100%;
        "
      >
        <h2>{{telainicial.0.box_1_titulo}}</h2>
        <p>{{telainicial.0.box_1_descricao}}</p>
      </div>
    </div>
    <hr class="divider" />
    <div class="box">
      <div
        class="inner-box"
        style="
          background: url(../img/placeholder-grande.png) no-repeat;
          background-size: 100% 100%;
        "
      >
        <h2>{{telainicial.0.box_2_titulo}}</h2>
        <p>{{telainicial.0.box_2_descricao}}</p>
      </div>
    </div>
  </div>
</section>

templates/hospitais/noticias_cards.html
<section class="noticias-cards main">
  <!-- PAINEL ESQUERDO -->
  <div class="noticias-card-left">
    {% for post in posts %}
    <div class="post">
      <div>
        <img src="{{post.foto_url}}" alt="" />
      </div>
      <div>
        <span class="post-category">Reta Final</span>
        <a class="post-title"> {{post.titulo}}</a>
        <span class="feed-post-description">{{post.descricao}}</span>
        <span class="feed-post-datetime">Há 4 minutoss</span>
      </div>
      {% if user.is_authenticated %}
      <a href="{% url 'editar' post.id %}"><span class="material-icons" style="font-size:18px;">edit</span></a> &nbsp;
      <a href="{% url 'deletar' post.id %}"><span class="material-icons" style="font-size:18px;">delete</span></a>
      {% endif %}
    </div>
    {% endfor %}
    <div class="load-more">
      <a id="btn__carregar_mais_noticias">VEJA MAIS</a>
    </div>
  </div>
  <!-- PAINEL DIREITO -->
  <div class="noticias-card-right">
    <div class="bastian-feed-item">
      <div class="noticias-card-title">
        Lorem ipsum dolor sit amet consectetur.
      </div>
      <div class="noticias-card-content">
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>

    <div class="bastian-feed-item">
      <div class="noticias-card-title">Lorem ipsum dolor sit.</div>
      <div class="noticias-card-content">
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>

    <div class="bastian-feed-item">
      <div class="noticias-card-title">Lorem ipsum dolor sit.</div>
      <div class="noticias-card-content">
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
    <div class="bastian-feed-item">
      <div class="noticias-card-title">Lorem ipsum dolor sit.</div>
      <div class="noticias-card-content">
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
        <div class="post-left">
          <div
            style="
              font-size: 15px;
              font-weight: 600;
              letter-spacing: -0.75px;
              line-height: 20px;
              color: rgb(51, 51, 51);
              margin-bottom: 0.5rem;
              font-family: opensans, opensans-bastian, Arial, sans-serif;
            "
          >
            <h3>Batalha dos votos</h3>
            <a href="">Por que conquistar a Pensilvânia é tão crucial?</a>
          </div>
          <div>
            <img
              src="/static/assets/img/placeholder-mini.png"
              width="100"
              height="100"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/posts/criar_post.html
{% extends 'hospitais/base.html' %}
{% block content %}
{% include 'hospitais/noticias_cards.html' %}
<div>
  {% for msg in messages %}
  <div class="alert {{msg.tgas}}">{{msg}}</div>
  {% endfor %}
  <form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%} {{form.as_p}}
    <button type="submit">Enviar</button>
  </form>
</div>

{% endblock content %}

templates/posts/deletar_post.html
{% block content %}
<h1>Deseja excluir {{post.nome_hospital}}?</h1>
<form method="POST">
  {% csrf_token %}
  <button type="submit">Excluir</button>
</form>

<a href="{% url 'jornal' %}">Voltar</a>
{% endblock content %}

templates/posts/editar_post.html
{% extends 'hospitais/base.html' %} {% block content %}
<div>
  <h1>Editar postagem</h1>
  <hr />
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="fieldWrapper">
      {{ form.nome_hospital.errors }}
      <label for="{{ form.nome_hospital.id_for_label }}">Título:</label> <br />
      {{ form.nome_hospital }}
    </div>

    <div class="fieldWrapper">
      {{ form.desc_hospital.errors }}
      <label for="{{ form.nome_hospital.id_desc_hospital }}">Descrição:</label><br />
      {{ form.desc_hospital }}
    </div>

    <figure>
      <img src="{{post.foto_url}}" class="image" alt="" srcset="" />
    </figure>
    <div class="fieldWrapper">
      {{ form.foto.errors }}
      <label for="{{ form.foto.id_foto }}">Foto:</label>
      {{ form.foto }}
    </div>

    {% comment %}
    <p>
      <label for="id_tipo_hospital">Tipo hospital:</label>
      <input
        type="text"
        name="tipo_hospital"
        value="público"
        maxlength="200"
        required=""
        id="id_tipo_hospital"
      />
    </p>
    {% endcomment %} {% comment %}
    <p>
      <label for="id_conceito_hospital">Conceito hospital:</label>
      <input
        type="text"
        name="conceito_hospital"
        value="teste"
        maxlength="200"
        required=""
        id="id_conceito_hospital"
      />
    </p>
    {% endcomment %}
    <hr />
    <button class="btn btn-danger" type="submit">Enviar</button>
  </form>
  <a href="{% url 'blog' %}">Voltar</a>
</div>
{% endblock content %}

usuarios/templates/usuarios/cadastre-se.html
{% extends 'hospitais/base.html' %} {% block content %}
<!-- Button trigger modal -->
<button
  type="button"
  class="btn btn-primary"
  data-bs-toggle="modal"
  data-bs-target="#exampleModal"
>
  Launch demo modal
</button>

<!-- Modal -->
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form method="POST" id="form-cadastre-se">
          {% csrf_token %} {{form}}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Fechar
        </button>
        <button type="submit" class="btn btn-primary" form="form-cadastre-se">
          Salvar Alterações
        </button>
      </div>
    </div>
  </div>
</div>
<script>
  var exampleModal = document.getElementById('exampleModal');
  exampleModal.show();
  exampleModal.addEventListener('show.bs.modal', function (event) {

  });
</script>
{% include 'hospitais/noticias_cards.html' %} {% endblock content %}

usuarios/templates/usuarios/form_login.html
{% extends 'hospitais/base.html' %} {% block content %}
<form method="post">
  {{form}} {% csrf_token %}
  <button type="submit">Logar</button>
</form>
{% endblock content %}